name: A4 DevOps

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'temurin'
            architecture: x64

      - name: Build with Maven
        run: mvn clean package
        working-directory: .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t safakhan26/java-app:latest .
        working-directory: . 

      - name: Push Docker Image
        run: docker push safakhan26/java-app:latest
